credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      user_role: admin
      password: "$2b$12$NZOjhl2C16KIZ5ym2sbGt.zBq6xK2QRuPWFm9t4fodrZNeRUAioHO"
    ccook:
      email: rbriggs@gmail.com
      name: Callan Cook
      user_role: student
      password: "$2b$12$NZOjhl2C16KIZ5ym2sbGt.zBq6xK2QRuPWFm9t4fodrZNeRUAioHO"
    yulei: 
      email: yulei3.li@northumbria.ac.uk
      name: Yulei LI
      user_role: admin
      password: "$2b$12$W0d6EyHrM69YJ5trRZBiFOHaiRRhTjyXHXy7RJMiYtEINgXZ8XJFm"
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
